###
# Show Inventory & Total Sales:

GET http://localhost:3000/api/v1/foods

### Before using below, remember to seed the db with bin/rails db:seed
### bin/rails db:reset can be used to reset while testing
###
# Buy 3 Chocolate Bars (use 4 times to trigger error)
PUT http://localhost:3000/api/v1/buy HTTP/1.1
Content-Type: application/json

{
    "name":"Chocolate Bar",
    "quantity": 3
}

###
# Buy more Mint Ice Cream than available.  Should return "SO SORRY!"
PUT http://localhost:3000/api/v1/buy HTTP/1.1
Content-Type: application/json

{
    "name":"Mint Ice Cream",
    "quantity": 13
}

###
# Item with high initial_qty to test sales totals
PUT http://localhost:3000/api/v1/buy HTTP/1.1
Content-Type: application/json

{
    "name":"Shaved Ice",
    "quantity": 3
}
